### ISSUE TITLE
it does not search anything; just opens spotify

### ISSUE THREAD

**Issue by OmarShawky1** [pywkm/ulauncher-spotify#16]
when i write `sp heart-alone` this should search for alone song by heart band. and this does not happen as following
![image](https://user-images.githubusercontent.com/51538094/104843990-2c098880-58d6-11eb-8db8-a1aa808a75fd.png)

**Comment by pywkm** [comment]
No, I'm sorry, `"sp phrase"` does not search for `phrase` in spotify. It never worked this way and I never said it should/will be.
